---
title: "Math Project Student Survey Data Cleaning Syntax"
editor_options: 
  chunk_output_type: console
---

## Data cleaning date: 2023-02-15
## Cleaned by: Crystal Lewis
## Project: Math intervention project
## Wave: Wave 1
## Data: Student Survey Data

```{r setup, include=FALSE, message = FALSE, warning = FALSE}
knitr::opts_chunk$set(echo = TRUE)

## libraries ##
library(tidyverse)
library(janitor)
library(stringr)
library(labelled)
library(readxl)
library(pointblank)
library(haven)
```

```{r Read in data}

# `read_study_datasource` would be a function in my package
# It would allow you to load data files from a yaml configuration
# that would load the csv and immediately rename the columns and
# remap the values to be ready for processing by the codebook.

svy <- read_study_datasource("data/w1_mathproj_stu_svy_raw.csv")

```

```{r (01) Review the data}

glimpse(svy)

```

```{r (02) Adjust cases as needed}

# Check for duplicates - 1347 is duplicated

svy %>%
  get_dupes(stu_id)

# Remove duplicates 
# Both surveys are complete - arrange by `svy_date` ascending

svy <- svy %>%
  arrange(svy_date) %>%
  distinct(stu_id, .keep_all = TRUE)

# Check - Review data after dropping the duplicates

svy

```

```{r (03) De-identify data}

# We don't need to drop the date column here, because in our codebook.yaml we've already
# marked it only for inclusion in to the "restricted" data export. In the other
# exports it will show up with all "redacted" missing values.

```

```{r (07) Normalize variables}

# This is taken care of by the definitions in w1_mathproj_stu_svy_codebook.yaml

```

```{r (08) Rename variables}

# This is also taken care of by the definitions in w1_mathproj_stu_svy_codebook.yaml

```

```{r (09) Update variable types}

# We don't need to do anything with variable types because they're all defined
# in our codebook.yaml. If it has any errors converting types, it will throw
# `pointblank` errors for us.

```

```{r (11) Construct variables}

# Construct `int`

svy <- svy %>%
  mutate(int = case_when(
    stu_id %in% c(1347, 1368, 1387) ~ "treatment",
    TRUE ~ "control"
  ))

# Review `int`

svy %>%
  tabyl(int)


```

```{r (12) Add missing values}

# The global remap takes care of this! Then the "missing" value is converted properly by the codebook
# definition 

```

```{r (13) Add metadata}

# Instead of manually doing all this, we just "appy" our codebook on the dataframe we just loaded

cleaned_svy <- apply_codebook(svy, "codebook.yaml")

# Now our dataframe should be properly typed and labeled, with all of the missing values taken
# care of as well!

```

```{r (14) Validate data}

# `apply_codebook` would also add pointblank validation checks using the constraints we defined in
# the codebook.yaml file.

interrogate(cleaned_svy)

```

```{r Export public data}

# In the public release, the date column will be filled with "redacted" missing values.

write_data_dictionary(cleaned_svy, "data/output/w1_mathproj_stu_svy_public_data_dictionary.csv", release = "public")

export_data_artifact(cleaned_svy, "data/output/w1_mathproj_stu_svy_public.sav", release = "public", format = "sav")

```

```{r Export restricted data}

write_data_dictionary(cleaned_svy, "data/output/w1_mathproj_stu_svy_restricted_data_dictionary.csv", release = "restricted")

export_data_artifact(cleaned_svy, "data/output/w1_mathproj_stu_svy_restricted.sav", release = "restricted", format = "sav")


```
